-- Creates the table to store affiliate user information
CREATE TABLE public.affiliates (
  -- The user ID from auth.users, acting as the primary key
  user_id UUID PRIMARY KEY REFERENCES public.profiles(id) ON DELETE CASCADE,
  
  -- The unique code for the affiliate link (e.g., "user123" in ?ref=user123)
  affiliate_code TEXT NOT NULL UNIQUE,
  
  -- The status of the affiliate account
  status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'inactive', 'pending')),
  
  -- Timestamp for when the affiliate was created
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Add comments for clarity
COMMENT ON TABLE public.affiliates IS 'Stores information about users who are affiliates.';
COMMENT ON COLUMN public.affiliates.user_id IS 'Links to the user''s profile.';
COMMENT ON COLUMN public.affiliates.affiliate_code IS 'Unique code used in referral links.';

-- Creates the table to track sales generated by affiliates
CREATE TABLE public.affiliate_sales (
  -- Unique identifier for each affiliate sale record
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  
  -- Links to the affiliate who generated the sale
  affiliate_id UUID NOT NULL REFERENCES public.affiliates(user_id) ON DELETE SET NULL,
  
  -- Links to the specific purchase record in user_purchases
  purchase_id UUID NOT NULL REFERENCES public.user_purchases(id) ON DELETE CASCADE,
  
  -- The calculated commission amount for this sale
  commission_amount NUMERIC(10, 2) NOT NULL,
  
  -- The commission rate at the time of sale (e.g., 0.3 for 30%)
  commission_rate NUMERIC(4, 2) NOT NULL,
  
  -- Status of the commission payment
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'paid', 'refunded')),
  
  -- Timestamp for when the sale was recorded
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Add comments for clarity
COMMENT ON TABLE public.affiliate_sales IS 'Tracks individual sales and commissions for affiliates.';
COMMENT ON COLUMN public.affiliate_sales.status IS 'Commission status: pending, paid, or refunded.';

-- Enable Row Level Security for both tables
ALTER TABLE public.affiliates ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.affiliate_sales ENABLE ROW LEVEL SECURITY;

-- Create RLS policies for affiliates table
CREATE POLICY "Users can view their own affiliate data"
  ON public.affiliates
  FOR SELECT
  TO authenticated
  USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own affiliate data"
  ON public.affiliates
  FOR INSERT
  TO authenticated
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update their own affiliate data"
  ON public.affiliates
  FOR UPDATE
  TO authenticated
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Admins can manage all affiliate data"
  ON public.affiliates
  FOR ALL
  TO authenticated
  USING (current_user_has_role('admin'))
  WITH CHECK (current_user_has_role('admin'));

-- Create RLS policies for affiliate_sales table
CREATE POLICY "Affiliates can view their own sales"
  ON public.affiliate_sales
  FOR SELECT
  TO authenticated
  USING (affiliate_id = auth.uid());

CREATE POLICY "System can insert affiliate sales"
  ON public.affiliate_sales
  FOR INSERT
  TO authenticated
  WITH CHECK (true);

CREATE POLICY "Admins can manage all affiliate sales"
  ON public.affiliate_sales
  FOR ALL
  TO authenticated
  USING (current_user_has_role('admin'))
  WITH CHECK (current_user_has_role('admin'));