// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kimrczuccegbvkxfbkjl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtpbXJjenVjY2VnYnZreGZia2psIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5Njc0NTYsImV4cCI6MjA2NTU0MzQ1Nn0.Q2hA5M-GG88VZANSlJRS3266vRIlplWxSK8X8z-_Pgk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);